name: Docker Image laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v3
    - name: "Creation de l'image pba dev"
      run: docker build . --file Dockerfile --tag laravel:dev
    - name: "lancement du container dev"
      run: docker compose up -d 
